export const ELEMENT_HEIGHT = 70;
export const STANDARD_ELEMENT_WIDTH = 350;
export const SUBACTIVITY_LEVEL_WIDTH_DECREMENT = 20;
export const SPACE_BETWEEN_ELEMENTS = 5;
export const PADDING_BETWEEN_ELEMENTS = 3;
